### ISSUE TITLE
投票也許可以即時送出，因為畫面太長很容易忘記送出

### ISSUE THREAD

**Issue by kiang** [PDIS/quadratic-voting-frontend#1]
目前投票必須點選送出才會紀錄，但清單實在太長，很容易讓人誤以為只要點選加減按鈕就可以完成投票，或許在點選同時就可以紀錄使用者票選結果，並且產生適當提示

然後投票點數累進概念會讓人第一時間誤以為程式錯誤，或許該有適當的提醒，而不是只有最上方的文字說明，其實看文字說明也很難立即搞懂這樣子做的用意是希望大家增加選擇的多樣性

**Comment by audreyt** [comment]
感謝，我也覺得即時送出比較好，不然至少要用 `onbeforeunload` 再次提醒使用者。 @billy3321

**Comment by audreyt** [comment]
已更新為即時儲存版本，投票過程不會有等待的狀況發生，感謝貢獻～
