### ISSUE TITLE
在投票網頁點選個別提案還是只有顯示三項內容而非全部提案內容

### ISSUE THREAD

**Issue by antigenius0910** [PDIS/quadratic-voting-frontend#3]
Hi, 

目前在投票網頁點選個別提案還是只有顯示三項內容(想解決什麼問題？這個問題為何很重要？期待本次專案成果之影響或效益？)而非全部提案內容

在提案當初有一個選項是 “全部內容投票前不公開” 當初的設計應該(?)是讓個別提案者無法抄襲其他提案者的提案細節所以只看得到提案大綱(三大項內容)

但是既然現在已經關閉提案修改功能並且開放投票 在我們的想像中不是應該公開所有的提案內容嗎?

**Comment by camychen** [comment]
公開這三項的內容是主辦方決定，其他內容有可能涉及提案者的創意及智慧財產。
開始投票後必須提供所有提案者的三項內容做參考，以進行投票。
公開內容的範圍也僅限這三項，並沒有公開提案所有內容。
